apiVersion: v1
kind: Service
metadata:
  name: habit-tracker-service
spec:
  selector:
    app: habit-tracker
  ports:
    - protocol: TCP
      port: 5011
      targetPort: 5011
      nodePort: 30011   # accessible on localhost:30011
  type: NodePort
